#!/usr/bin/env bash

# GIT FUNCTIONS
git_branch() {
    git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

# TERMINAL PROMPT
PS1=""
PS1+="┌ 💁 \[\e[0;93m\]\u\[\e[m\]" # username
PS1+=" @ 💻 \h " # space
PS1+="in 📁 \[\e[0;95m\]\w\[\e[m\]" # current directory
PS1+="\[\e[0;92m\]\$(git_branch)\[\e[m\]" # current branch
PS1+="\n" # space
PS1+="└❯ " # end prompt
export PS1;
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
